<?php
declare(strict_types=1);

namespace App\Command;

use Cake\Command\Command;
use Cake\Console\Arguments;
use Cake\Console\ConsoleIo;
use Cake\Console\ConsoleOptionParser;
use Cake\Database\Connection;
use Cake\Database\Driver\Mysql;
use Cake\Database\Driver\Postgres;
use Cake\Datasource\ConnectionManager;
use ReflectionClass;
use RuntimeException;
use Throwable;

/**
 * Uebernimmt die Nutzdaten einmalig aus der alten MySQL-Datenbank in die neue
 * PostgreSQL-Datenbank.
 *
 *     bin/cake import_mysql --confirm
 *
 * Nach dem Abbau von mysql-0 wird dieses Kommando geloescht — es hat genau
 * einen Einsatz.
 *
 * ## Warum nicht einfach der mysqldump, umgeschrieben?
 *
 * Weil er still Daten beschaedigt. Der Dump maskiert Sonderzeichen innerhalb
 * der Zeichenketten auf MySQL-Art: eine Beschreibung enthaelt dort etwa
 * "…SIU-Service\r\ncall with BaseIT". PostgreSQL laeuft mit
 * standard_conforming_strings = on, und dort ist \r\n kein Zeilenumbruch,
 * sondern ein Backslash, ein r, ein Backslash, ein n. Das Ergebnis waere eine
 * Datenbank, die richtig aussieht, in der aber ein Teil der Beschreibungen
 * kaputt ist. Dasselbe gilt fuer \' und \\.
 *
 * Deshalb geht hier kein Wert je als Literal in ein SQL-Statement: gelesen
 * wird ueber PDO, geschrieben ueber gebundene Parameter.
 *
 * ## Die drei Fallen, die das Kommando abfaengt
 *
 * 1. **Reihenfolge.** Die Fremdschluessel erzwingen groups → users →
 *    mandanten → bookings.
 * 2. **IDs.** Sie werden ausdruecklich mituebernommen, sonst zeigen die
 *    Fremdschluessel ins Leere. Das geht nur, weil die Baseline-Migration
 *    "GENERATED BY DEFAULT AS IDENTITY" erzeugt und nicht "ALWAYS".
 * 3. **Sequenzen.** MySQL zieht den AUTO_INCREMENT-Zaehler beim Einfuegen
 *    fester IDs mit, PostgreSQL nicht. Ohne das abschliessende setval() liefe
 *    die erste neu angelegte Buchung in eine Verletzung des
 *    Eindeutigkeitsschlüssels. (Dieselbe Falle in den Tests: siehe
 *    tests/Fixture/AppFixture.php.)
 */
class ImportMysqlCommand extends Command
{
    /**
     * Reihenfolge ist bindend — sie folgt den Fremdschluesseln.
     *
     * Die Tabellen bookings_backup_20260501, users_backup_20260501 und
     * schema_upgrade_log stehen bewusst NICHT hier: das sind Momentaufnahmen
     * und ein Protokoll eines einmaligen Upgrade-Skripts. Sie bleiben im
     * archivierten MySQL-Dump.
     *
     * @var list<string>
     */
    private const TABLES = ['groups', 'users', 'mandanten', 'bookings'];

    /**
     * Spalten, deren Rand-Leerzeichen beim Uebernehmen entfernt werden.
     *
     * Grund ist eine Eigenheit von MySQL, die sonst zu sichtbarem Unsinn
     * fuehrt: die Kollation utf8mb3_general_ci vergleicht mit PAD SPACE,
     * "PRB98726 " und "PRB98726" sind dort also derselbe Wert. PostgreSQL
     * unterscheidet sie. In den Produktionsdaten stecken genau drei solche
     * Werte (zwei Tickets, ein PSP) — unbehandelt erschiene jeder davon im
     * Auswahlfeld doppelt, einmal mit und einmal ohne Leerzeichen.
     *
     * Das Trimmen aendert das Verhalten also nicht, es erhaelt es. Umgekehrt
     * waere die unveraenderte Uebernahme die eigentliche Verhaltensaenderung.
     *
     * Bewusst NICHT dabei: description. Das ist Fliesstext, dort hat die
     * Kollation nie eine Rolle gespielt, und ein stiller Eingriff in
     * Kundeninhalte waere nicht zu rechtfertigen.
     *
     * @var array<string, list<string>>
     */
    private const TRIM_COLUMNS = [
        'bookings' => ['ticket', 'bookingpsp'],
    ];

    /**
     * Protokoll der normalisierten Werte — wird am Ende ausgegeben, damit
     * keine Aenderung an den Daten unbemerkt bleibt.
     *
     * @var list<string>
     */
    private array $trimmed = [];

    /**
     * @param \Cake\Console\ConsoleOptionParser $parser Parser
     * @return \Cake\Console\ConsoleOptionParser
     */
    public function buildOptionParser(ConsoleOptionParser $parser): ConsoleOptionParser
    {
        return $parser
            ->setDescription('Uebernimmt die Nutzdaten einmalig aus MySQL nach PostgreSQL.')
            ->addOption('confirm', [
                'boolean' => true,
                'help' => 'Ohne diese Angabe wird nur geprüft und nichts geschrieben.',
            ]);
    }

    /**
     * @param \Cake\Console\Arguments $args Argumente
     * @param \Cake\Console\ConsoleIo $io Ein-/Ausgabe
     * @return int
     */
    public function execute(Arguments $args, ConsoleIo $io): int
    {
        $target = ConnectionManager::get('default');
        assert($target instanceof Connection);
        $source = $this->legacyConnection();

        if (!$target->getDriver() instanceof Postgres) {
            $io->error('Die Zielverbindung "default" ist kein PostgreSQL. Abbruch.');

            return static::CODE_ERROR;
        }

        $io->out('Quelle : ' . $this->describe($source));
        $io->out('Ziel   : ' . $this->describe($target));
        $io->hr();

        $plan = [];
        foreach (self::TABLES as $table) {
            $columns = $this->sharedColumns($source, $target, $table, $io);
            $sourceRows = $this->countRows($source, $table);
            $targetRows = $this->countRows($target, $table);

            if ($targetRows > 0) {
                $io->error(sprintf(
                    'Zieltabelle "%s" enthält bereits %d Zeilen. Der Import läuft nur in leere '
                    . 'Tabellen; sonst kollidieren die IDs. Zum Wiederholen: '
                    . 'TRUNCATE %s RESTART IDENTITY CASCADE;',
                    $table,
                    $targetRows,
                    implode(', ', array_reverse(self::TABLES)),
                ));

                return static::CODE_ERROR;
            }

            $io->out(sprintf('  %-12s %5d Zeilen, %d Spalten', $table, $sourceRows, count($columns)));
            $plan[$table] = ['columns' => $columns, 'expected' => $sourceRows];
        }

        if (!$args->getOption('confirm')) {
            $io->hr();
            $io->warning('Trockenlauf — es wurde nichts geschrieben. Mit --confirm ausführen.');

            return static::CODE_SUCCESS;
        }

        $io->hr();
        $target->begin();
        try {
            foreach (self::TABLES as $table) {
                $copied = $this->copyTable($source, $target, $table, $plan[$table]['columns']);

                if ($copied !== $plan[$table]['expected']) {
                    throw new RuntimeException(sprintf(
                        'Tabelle "%s": %d Zeilen übernommen, erwartet waren %d.',
                        $table,
                        $copied,
                        $plan[$table]['expected'],
                    ));
                }
                $io->success(sprintf('  %-12s %5d Zeilen übernommen', $table, $copied));
            }

            foreach (self::TABLES as $table) {
                $next = $this->resetSequence($target, $table);
                $io->out(sprintf('  %-12s nächste id = %d', $table, $next));
            }

            $target->commit();
        } catch (Throwable $e) {
            $target->rollback();
            $io->error('Import abgebrochen, nichts geschrieben: ' . $e->getMessage());

            return static::CODE_ERROR;
        }

        $io->hr();
        foreach (self::TABLES as $table) {
            $io->out(sprintf(
                '  %-12s Quelle %5d | Ziel %5d',
                $table,
                $plan[$table]['expected'],
                $this->countRows($target, $table),
            ));
        }

        if ($this->trimmed) {
            $io->hr();
            $io->warning(sprintf(
                '%d Wert(e) um Rand-Leerzeichen bereinigt (MySQL verglich mit PAD SPACE, '
                . 'PostgreSQL nicht — ohne das erschienen sie doppelt im Auswahlfeld):',
                count($this->trimmed),
            ));
            foreach ($this->trimmed as $line) {
                $io->out('  ' . $line);
            }
        }

        $io->success('Fertig.');

        return static::CODE_SUCCESS;
    }

    /**
     * Verbindung zur abzuloesenden MySQL-Datenbank, aus den MYSQL_*-Variablen,
     * die bis zum Abbau von mysql-0 im Secret mytime-secret stehen.
     */
    private function legacyConnection(): Connection
    {
        ConnectionManager::setConfig('legacy_mysql', [
            'className' => Connection::class,
            'driver' => Mysql::class,
            'host' => env('MYSQL_HOST', 'mysql'),
            'port' => (int)env('MYSQL_PORT', '3306'),
            'username' => env('MYSQL_USER', 'mytime'),
            'password' => env('MYSQL_PASS', ''),
            'database' => env('MYSQL_DB', 'mytime'),
            'encoding' => 'utf8mb4',
            'timezone' => 'UTC',
            'persistent' => false,
            'quoteIdentifiers' => true,
            'cacheMetadata' => false,
        ]);

        $connection = ConnectionManager::get('legacy_mysql');
        assert($connection instanceof Connection);

        return $connection;
    }

    /**
     * Kurzbeschreibung einer Verbindung fuer die Ausgabe (Treiber, Host, Datenbank).
     */
    private function describe(Connection $connection): string
    {
        $config = $connection->config();

        return sprintf(
            '%s @ %s/%s',
            (new ReflectionClass($connection->getDriver()))->getShortName(),
            $config['host'] ?? '?',
            $config['database'] ?? '?',
        );
    }

    /**
     * Spalten, die es in beiden Datenbanken gibt. Alles, was nur die Quelle
     * kennt, wird gemeldet statt stillschweigend fallengelassen — sonst
     * verschwinden Daten, ohne dass es jemand merkt.
     *
     * @return list<string>
     */
    private function sharedColumns(Connection $source, Connection $target, string $table, ConsoleIo $io): array
    {
        $sourceColumns = $source->getSchemaCollection()->describe($table)->columns();
        $targetColumns = $target->getSchemaCollection()->describe($table)->columns();

        $onlyInSource = array_diff($sourceColumns, $targetColumns);
        if ($onlyInSource) {
            $io->warning(sprintf(
                '  %s: Spalte(n) %s gibt es nur in MySQL und werden NICHT übernommen.',
                $table,
                implode(', ', $onlyInSource),
            ));
        }
        $onlyInTarget = array_diff($targetColumns, $sourceColumns);
        if ($onlyInTarget) {
            $io->out(sprintf(
                '  %s: Spalte(n) %s sind neu und bleiben auf ihrem Vorgabewert.',
                $table,
                implode(', ', $onlyInTarget),
            ));
        }

        return array_values(array_intersect($sourceColumns, $targetColumns));
    }

    /**
     * Zeilenzahl einer Tabelle - dient dem Abgleich Quelle gegen Ziel.
     */
    private function countRows(Connection $connection, string $table): int
    {
        $statement = $connection->execute(
            'SELECT COUNT(*) FROM ' . $connection->getDriver()->quoteIdentifier($table),
        );

        return (int)$statement->fetch()[0];
    }

    /**
     * Kopiert eine Tabelle. Werte gehen als gebundene Parameter durch, die
     * Umwandlung in den Zieltyp uebernimmt der Typ-Layer von CakePHP anhand
     * des Zielschemas — daraus wird aus MySQLs 0/1 ein echtes PostgreSQL-
     * BOOLEAN.
     *
     * @param list<string> $columns Spalten
     */
    private function copyTable(Connection $source, Connection $target, string $table, array $columns): int
    {
        $schema = $target->getSchemaCollection()->describe($table);
        $types = [];
        foreach ($columns as $column) {
            $types[$column] = $schema->getColumnType($column);
        }

        $quote = $source->getDriver();
        $select = implode(', ', array_map(fn(string $c): string => $quote->quoteIdentifier($c), $columns));
        $rows = $source->execute(sprintf(
            'SELECT %s FROM %s ORDER BY %s',
            $select,
            $quote->quoteIdentifier($table),
            $quote->quoteIdentifier('id'),
        ))->fetchAll('assoc');

        if (!$rows) {
            return 0;
        }

        $trim = array_intersect(self::TRIM_COLUMNS[$table] ?? [], $columns);

        // Ein Statement je Zeile: bei rund 500 Zeilen ist die Laufzeit
        // belanglos, und ein Fehler laesst sich der Zeile zuordnen.
        foreach ($rows as $row) {
            $values = [];
            foreach ($columns as $column) {
                $value = $row[$column];
                if ($value !== null && in_array($column, $trim, true)) {
                    $trimmed = trim((string)$value);
                    if ($trimmed !== $value) {
                        $this->trimmed[] = sprintf('%s.%s: "%s" → "%s"', $table, $column, $value, $trimmed);
                    }
                    $value = $trimmed;
                }
                $values[$column] = $value;
            }

            $target->insertQuery()
                ->insert($columns, $types)
                ->into($table)
                ->values($values)
                ->execute();
        }

        return count($rows);
    }

    /**
     * Setzt die Identity-Sequenz auf den naechsten freien Wert und gibt ihn
     * zurueck. is_called = false, damit nextval() genau diesen Wert liefert;
     * bei leerer Tabelle waere setval(seq, 0) unzulaessig.
     */
    private function resetSequence(Connection $connection, string $table): int
    {
        $quoted = $connection->getDriver()->quoteIdentifier($table);
        $statement = $connection->execute(sprintf(
            "SELECT setval(
                 pg_get_serial_sequence('%s', 'id'),
                 COALESCE((SELECT MAX(id) FROM %s), 0) + 1,
                 false
             )",
            $quoted,
            $quoted,
        ));

        return (int)$statement->fetch()[0];
    }
}
