<?php
declare(strict_types=1);

use Migrations\BaseMigration;

/**
 * Das vollstaendige Schema von mytime in einer Migration.
 *
 * Sie loest die fuenf urspruenglichen Migrationen ab (jetzt unter
 * config/Migrations/archive-mysql/), die den Weg von der ersten Fassung bis
 * zum Stand vom Mai 2026 Schritt fuer Schritt nachbauten — und dabei
 * MySQL-Eigenheiten mitschleppten, die PostgreSQL nicht kennt: 'signed' fuer
 * UNSIGNED-Spalten, 'after' fuer die Spaltenreihenfolge und Backticks in
 * rohen execute()-Aufrufen.
 *
 * Ausserdem hatte die Produktionsdatenbank Spalten, die in keiner Migration
 * standen (users.password, oidc_sub, first_name, last_name) — sie stammten aus
 * einem von Hand gefahrenen SQL-Skript. Hier stehen sie wieder mit drin, damit
 * Migrationen und Wirklichkeit dasselbe sagen.
 *
 * Bewusste Abweichungen vom alten MySQL-Schema, jeweils mit Grund an Ort und
 * Stelle vermerkt. Der wichtigste Punkt vorab: Primaerschluessel sind
 * 'integer', nicht 'biginteger'. PostgreSQL macht daraus
 * "INTEGER GENERATED BY DEFAULT AS IDENTITY", SQLite (die Testdatenbank)
 * dagegen vergibt PRIMARY KEY AUTOINCREMENT ausschliesslich fuer INTEGER —
 * mit biginteger wuerde dort jedes Einfuegen ohne explizite ID scheitern.
 * int4 reicht bis 2.147.483.647; die hoechste Buchungs-ID lag beim Umstieg
 * bei 499.
 */
class InitialPostgresSchema extends BaseMigration
{
    /**
     * @return void
     */
    public function change(): void
    {
        // Reihenfolge folgt den Fremdschluesseln: groups vor users, users und
        // mandanten vor bookings. Die automatische Umkehr von change() raeumt
        // in genau umgekehrter Reihenfolge ab und bleibt damit gueltig.
        $this->table('groups')
            ->addColumn('name', 'string', [
                'default' => null,
                'limit' => 100,
                'null' => false,
            ])
            ->addColumn('created', 'datetime', ['default' => null, 'null' => true])
            ->addColumn('modified', 'datetime', ['default' => null, 'null' => true])
            ->addIndex(['name'], ['unique' => true, 'name' => 'uniq_groups_name'])
            ->create();

        $this->table('users')
            ->addColumn('group_id', 'integer', ['default' => null, 'null' => false])
            // Frueher TINYINT(1) mit 0/1 — die MySQL-Schreibweise fuer einen
            // Wahrheitswert. PostgreSQL hat einen echten BOOLEAN.
            ->addColumn('is_admin', 'boolean', ['default' => false, 'null' => false])
            ->addColumn('username', 'string', ['default' => null, 'limit' => 255, 'null' => true])
            ->addColumn('email', 'string', ['default' => null, 'limit' => 255, 'null' => true])
            ->addColumn('password', 'string', ['default' => null, 'limit' => 255, 'null' => true])
            ->addColumn('oidc_sub', 'string', ['default' => null, 'limit' => 255, 'null' => true])
            ->addColumn('first_name', 'string', ['default' => null, 'limit' => 255, 'null' => true])
            ->addColumn('last_name', 'string', ['default' => null, 'limit' => 255, 'null' => true])
            ->addColumn('created', 'datetime', ['default' => null, 'null' => true])
            ->addColumn('modified', 'datetime', ['default' => null, 'null' => true])
            ->addIndex(['oidc_sub'], ['unique' => true, 'name' => 'uniq_users_oidc_sub'])
            ->addIndex(['group_id'], ['name' => 'idx_users_group_id'])
            ->addForeignKey('group_id', 'groups', 'id', [
                'constraint' => 'fk_users_group_id_groups_id',
                'delete' => 'RESTRICT',
                'update' => 'CASCADE',
            ])
            ->create();

        $this->table('mandanten')
            ->addColumn('name', 'string', [
                'default' => null,
                'limit' => 100,
                'null' => false,
            ])
            ->addColumn('created', 'datetime', ['default' => null, 'null' => true])
            ->addColumn('modified', 'datetime', ['default' => null, 'null' => true])
            ->addIndex(['name'], ['unique' => true, 'name' => 'uniq_mandanten_name'])
            ->create();

        $this->table('bookings')
            ->addColumn('user_id', 'integer', ['default' => null, 'null' => false])
            ->addColumn('group_id', 'integer', ['default' => null, 'null' => false])
            ->addColumn('mandant_id', 'integer', ['default' => null, 'null' => false])
            // In MySQL stand hier DEFAULT (curdate()) — ein Ausdrucks-Default,
            // den der Schema-Layer von CakePHP nicht abbildet. Die Anwendung
            // setzt das Feld ohnehin immer, BookingsTable erzwingt es per
            // Validierung.
            ->addColumn('bookingdate', 'date', ['default' => null, 'null' => false])
            ->addColumn('ticket', 'string', ['default' => null, 'limit' => 15, 'null' => false])
            ->addColumn('bookingpsp', 'string', ['default' => null, 'limit' => 20, 'null' => false])
            ->addColumn('description', 'text', ['default' => null, 'null' => false])
            ->addColumn('minutes', 'integer', ['default' => null, 'null' => false])
            ->addColumn('kunde', 'string', ['default' => 'FRQ', 'limit' => 20, 'null' => false])
            ->addColumn('created', 'datetime', ['default' => null, 'null' => false])
            ->addColumn('modified', 'datetime', ['default' => null, 'null' => false])
            ->addIndex(['user_id'], ['name' => 'idx_bookings_user_id'])
            ->addIndex(['group_id'], ['name' => 'idx_bookings_group_id'])
            ->addIndex(['mandant_id'], ['name' => 'idx_bookings_mandant_id'])
            // Neu gegenueber MySQL: jede Abfrage der Anwendung sortiert oder
            // filtert nach dem Buchungsdatum (Monatsauswertung, Exporte,
            // Ticket-Liste), einen Index dafuer gab es aber nie.
            ->addIndex(['bookingdate'], ['name' => 'idx_bookings_bookingdate'])
            ->addForeignKey('user_id', 'users', 'id', [
                'constraint' => 'fk_bookings_user_id_users_id',
                'delete' => 'CASCADE',
                'update' => 'CASCADE',
            ])
            ->addForeignKey('group_id', 'groups', 'id', [
                'constraint' => 'fk_bookings_group_id_groups_id',
                'delete' => 'RESTRICT',
                'update' => 'CASCADE',
            ])
            ->addForeignKey('mandant_id', 'mandanten', 'id', [
                'constraint' => 'fk_bookings_mandant_id_mandanten_id',
                'delete' => 'RESTRICT',
                'update' => 'CASCADE',
            ])
            ->create();

        // Das je Monat vom Kunden freigegebene Approval (die "Approved"-Mail
        // als PDF) liegt in der Datenbank, nicht im Dateisystem: die Anwendung
        // laeuft im Cluster ohne dauerhaften Datentraeger, eine Datei ueberlebte
        // keinen Neustart des Pods.
        $this->table('approvals')
            ->addColumn('user_id', 'integer', ['default' => null, 'null' => false])
            ->addColumn('mandant_id', 'integer', ['default' => null, 'null' => true])
            ->addColumn('year', 'integer', ['default' => null, 'null' => false])
            ->addColumn('month', 'integer', ['default' => null, 'null' => false])
            ->addColumn('filename', 'string', ['default' => null, 'limit' => 255, 'null' => false])
            ->addColumn('mime', 'string', [
                'default' => 'application/pdf',
                'limit' => 100,
                'null' => false,
            ])
            // Ohne 'limit': das steuerte in MySQL nur die Wahl zwischen
            // TINYBLOB/BLOB/MEDIUMBLOB/LONGBLOB. PostgreSQL hat BYTEA, das
            // bis 1 GB traegt. Die Obergrenze fuer Uploads bleibt eine Regel
            // der Anwendung (ApiController), keine des Datentyps.
            ->addColumn('content', 'binary', ['default' => null, 'null' => false])
            ->addColumn('byte_size', 'integer', ['default' => 0, 'null' => false])
            ->addColumn('uploaded_by', 'string', ['default' => null, 'limit' => 255, 'null' => true])
            ->addColumn('created', 'datetime', ['default' => null, 'null' => true])
            ->addColumn('modified', 'datetime', ['default' => null, 'null' => true])
            // Ein Approval je Nutzer/Mandant/Monat; ein erneuter Upload
            // ueberschreibt.
            ->addIndex(['user_id', 'mandant_id', 'year', 'month'], [
                'unique' => true,
                'name' => 'approvals_period_unique',
            ])
            // Fremdschluessel, die es in der alten Fassung nicht gab.
            ->addForeignKey('user_id', 'users', 'id', [
                'constraint' => 'fk_approvals_user_id_users_id',
                'delete' => 'CASCADE',
                'update' => 'CASCADE',
            ])
            ->addForeignKey('mandant_id', 'mandanten', 'id', [
                'constraint' => 'fk_approvals_mandant_id_mandanten_id',
                'delete' => 'CASCADE',
                'update' => 'CASCADE',
            ])
            ->create();

        // Der Eindeutigkeitsindex oben greift nicht, wenn mandant_id NULL ist:
        // zwei NULL-Werte gelten in SQL nie als gleich (in MySQL genauso).
        // ApprovalsTable::findForPeriod() sucht aber genau mit
        // "mandant_id IS NULL" — ohne diesen Teilindex koennten dort durch zwei
        // gleichzeitige Uploads Dubletten entstehen, die die Abfrage dann
        // willkuerlich aufloest. Teilindizes kennt SQLite zwar auch, der
        // Migrations-Adapter bildet sie aber nicht ab; deshalb der Umweg ueber
        // rohes SQL und die Beschraenkung auf PostgreSQL.
        //
        // ⚠ Der Bezeichner lautet 'pgsql', nicht 'postgres'. PostgresAdapter
        // ueberschreibt getAdapterType() genau dafuer ("Hardcoded because the
        // parent implementation reads an option that is based off of
        // Database\Driver names which is postgres, but pgsql is required for
        // compatibility"). Ein Vergleich mit 'postgres' waere immer falsch —
        // und zwar lautlos: die Migration liefe durch, der Index fehlte.
        if (in_array($this->getAdapter()->getAdapterType(), ['pgsql', 'postgres'], true)) {
            $this->execute(
                'CREATE UNIQUE INDEX approvals_period_null_mandant
                 ON approvals (user_id, year, month) WHERE mandant_id IS NULL'
            );
        }
    }
}
